language: java
jdk:
  - openjdk11

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/ .m2/repository'
    - '$HOME/ .gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r jambe-service *
  - mkdir -p deploy
  - mv jambe-service.zip deploy/jambe-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: jambe-service-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: jamber-service-build
    key: jambe-service.zip
    bundle_type: zip
    application: jambe-service
    deployment_group: jambe-service-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - cksgnlcjswoo@naver.com
